#!/bin/bash
set -e

if [ -z $SNSTERGUARD ] ; then exit 1; fi
DIR=`dirname $0`
cd `dirname $0`

# do something visible
#ip route add 0.0.0.0/0 via 192.168.1.254

###############################################################################

DEBIAN_FRONTEND=noninteractive apt-get update && apt full-upgrade -y

DEBIAN_FRONTEND=noninteractive apt-get install net-tools nano gedit curl wget sed  bind9 bind9utils bind9-doc dnsutils xfce4 -y

###############################################################################

#echo "172.16.110.10     www.snsterproject.fr" >> /etc/hosts

#curl --max-time 2 -f -I http://172.16.110.10/

cp /etc/bind/named.conf /etc/bind/named.conf.bak

cp /etc/bind/named.conf.default-zones  /etc/bind/named.conf.default-zones.bak

cp /etc/bind/named.conf.local  /etc/bind/named.conf.local.bak

#Déclaration de la zone « tonytechstore.tech » :

###############################################################################

echo -e "

/* Déclaration de la zone \"tonytechstore.tech\" */

zone \"tonytechstore.tech\" in {
        type Master;
        file \"/etc/bind/db.tonytechstore.tech\";
};

zone \"110.16.172.in-addr.arpa\" {
    type master;
    file \"/etc/bind/db.172.16.110\";
};

zone \"1.168.192.in-addr.arpa\" {
    type master;
    file \"/etc/bind/db.192.168.1\";
};

zone \"watchmovies.movie\" {
    type forward;
    forwarders {172.16.120.10;}; 
};

" >> /etc/bind/named.conf.local

###############################################################################

echo -e "

// ACL
acl trustednet {
        localhost;
        localnets;
        172.16.110.0/24;
        172.16.120.0/24;
        192.168.1.0/24;
};

//=====================================================================

options {
        directory \"/var/cache/bind\";

        // If there is a firewall between you and nameservers you want
        // to talk to, you may need to fix the firewall to allow multiple
        // ports to talk.  See http://www.kb.cert.org/vuls/id/800113

        // If your ISP provided one or more IP addresses for stable
        // nameservers, you probably want to use them as forwarders.
        // Uncomment the following block, and insert the addresses replacing
        // the all-0's placeholder.

        //=================================================================     

        recursion yes;
        allow-query { trustednet; };
        allow-query-cache { trustednet; };
        allow-recursion { trustednet; };


        //===================================================================== 

        forwarders {
                1.1.1.1;
                1.0.0.1;
                8.8.8.8;
                8.8.4.4;
         };

        //========================================================================
        // If BIND logs error messages about the root key being expired,
        // you will need to update your keys.  See https://www.isc.org/bind-keys
        //========================================================================

        dnssec-validation no;
        listen-on-v6 { none; };
        listen-on port 53 { 127.0.0.1; 172.16.110.0/24; };

        //========================================================================

};

" > /etc/bind/named.conf.options

#sudo touch db.tonytechstore.tech

###############################################################################

echo -e "

; BIND reverse data file for tonytechstore.tech
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
\$TTL    86400
@       IN      SOA     tonytecstore.tech. admin.tonytechstore.tech. (
                       20230801         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                          86400 )       ; Negative Cache TTL
;
@       IN      NS      tonytechstore.tech.
@       IN      A       172.16.110.20
srvdns  IN      A       172.16.110.20
srvweb  IN      A       172.16.110.10
srvdhcp IN      A       192.168.1.254
www     IN      CNAME   srvweb


" > /etc/bind/db.tonytechstore.tech


#named-checkzone tonytechstore.tech db.tonytechstore.tech

###############################################################################

#sudo touch db.172.16.110

echo -e "

;
; BIND reverse data file for tonytechstore.tech
;
\$TTL    604800
@       IN      SOA     tonytechstore.tech. admin.tonytechstore.tech. (
                        20230731        ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                         604800 )       ; Negative Cache TTL
;
@       IN      NS      tonytechstore.tech.
20      IN      PTR     srvdns.tonytechstore.tech.
10      IN      PTR     srvweb.tonytechstore.tech.
10      IN      PTR     www.tonytechstore.tech.

" > /etc/bind/db.172.16.110

#named-checkzone 110.16.172.in-addr.arpa db.172.16.110

###############################################################################

#sudo touch db.192.168.1

echo -e "

;
; BIND reverse data file for tonytechstore.tech
;
\$TTL    604800
@       IN      SOA     tonytechstore.tech. admin.tonytechstore.tech. (
                        20230631        ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                         604800 )       ; Negative Cache TTL
;
@       IN      NS      tonytechstore.tech.
254     IN      PTR     srvdhcp.tonytechstore.tech.

" > /etc/bind/db.192.168.1

###############################################################################

systemctl reload bind9

###############################################################################

systemctl restart bind9

#named-checkzone 1.168.192.in-addr.arpa db.192.168.1

###############################################################################
